/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BoincAPIWrapper */

#ifndef _Included_BoincAPIWrapper
#define _Included_BoincAPIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BoincAPIWrapper
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_init
  (JNIEnv *, jclass);

/*
 * Class:     BoincAPIWrapper
 * Method:    finish
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_finish
  (JNIEnv *, jclass, jint);

/*
 * Class:     BoincAPIWrapper
 * Method:    getInitData
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_getInitData
  (JNIEnv *, jclass, jobject);

/*
 * Class:     BoincAPIWrapper
 * Method:    parseInitDataFile
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_parseInitDataFile
  (JNIEnv *, jclass);

/*
 * Class:     BoincAPIWrapper
 * Method:    sendTrickleUp
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_sendTrickleUp
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     BoincAPIWrapper
 * Method:    setMinCheckpointPeriod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_setMinCheckpointPeriod
  (JNIEnv *, jclass);

/*
 * Class:     BoincAPIWrapper
 * Method:    checkpointCompleted
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_checkpointCompleted
  (JNIEnv *, jclass);

/*
 * Class:     BoincAPIWrapper
 * Method:    fractionDone
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_fractionDone
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     BoincAPIWrapper
 * Method:    suspendOtherActivities
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_suspendOtherActivities
  (JNIEnv *, jclass);

/*
 * Class:     BoincAPIWrapper
 * Method:    resumeOtherActivities
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_resumeOtherActivities
  (JNIEnv *, jclass);

/*
 * Class:     BoincAPIWrapper
 * Method:    reportAppStatus
 * Signature: (DDD)I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_reportAppStatus
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     BoincAPIWrapper
 * Method:    timeToCheckpoint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_timeToCheckpoint
  (JNIEnv *, jclass);

/*
 * Class:     BoincAPIWrapper
 * Method:    beginnCriticalSection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_BoincAPIWrapper_beginnCriticalSection
  (JNIEnv *, jclass);

/*
 * Class:     BoincAPIWrapper
 * Method:    tryCrititalSection
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_tryCrititalSection
  (JNIEnv *, jclass);

/*
 * Class:     BoincAPIWrapper
 * Method:    endCriticalSection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_BoincAPIWrapper_endCriticalSection
  (JNIEnv *, jclass);

/*
 * Class:     BoincAPIWrapper
 * Method:    needNetwork
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_BoincAPIWrapper_needNetwork
  (JNIEnv *, jclass);

/*
 * Class:     BoincAPIWrapper
 * Method:    networkPoll
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_networkPoll
  (JNIEnv *, jclass);

/*
 * Class:     BoincAPIWrapper
 * Method:    networkDone
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_BoincAPIWrapper_networkDone
  (JNIEnv *, jclass);

/*
 * Class:     BoincAPIWrapper
 * Method:    networkUsage
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_BoincAPIWrapper_networkUsage
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     BoincAPIWrapper
 * Method:    isStandalone
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_isStandalone
  (JNIEnv *, jclass);

/*
 * Class:     BoincAPIWrapper
 * Method:    opsPerCpuSec
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_BoincAPIWrapper_opsPerCpuSec
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     BoincAPIWrapper
 * Method:    opsCumulative
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_BoincAPIWrapper_opsCumulative
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     BoincAPIWrapper
 * Method:    setCreditClaim
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_BoincAPIWrapper_setCreditClaim
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     BoincAPIWrapper
 * Method:    receiveTrickleDown
 * Signature: ([CI)I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_receiveTrickleDown
  (JNIEnv *, jclass, jcharArray, jint);

/*
 * Class:     BoincAPIWrapper
 * Method:    initOptions
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_initOptions
  (JNIEnv *, jclass, jint);

/*
 * Class:     BoincAPIWrapper
 * Method:    getStatus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_getStatus
  (JNIEnv *, jclass, jint);

/*
 * Class:     BoincAPIWrapper
 * Method:    getFractionDone
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_BoincAPIWrapper_getFractionDone
  (JNIEnv *, jclass);

/*
 * Class:     BoincAPIWrapper
 * Method:    registerTimerCallback
 * Signature: (Ljava/lang/Runnable;)V
 */
JNIEXPORT void JNICALL Java_BoincAPIWrapper_registerTimerCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     BoincAPIWrapper
 * Method:    workerThreadCpuTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_BoincAPIWrapper_workerThreadCpuTime
  (JNIEnv *, jclass);

/*
 * Class:     BoincAPIWrapper
 * Method:    initParallel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_initParallel
  (JNIEnv *, jclass);

/*
 * Class:     BoincAPIWrapper
 * Method:    webGraphicsUrl
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_BoincAPIWrapper_webGraphicsUrl
  (JNIEnv *, jclass, jstring);

/*
 * Class:     BoincAPIWrapper
 * Method:    removeDesktopAddr
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_BoincAPIWrapper_removeDesktopAddr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     BoincAPIWrapper
 * Method:    setMacPList
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_setMacPList
  (JNIEnv *, jclass);

/*
 * Class:     BoincAPIWrapper
 * Method:    setMacIcon
 * Signature: (Ljava/lang/String;[CJ)I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_setMacIcon
  (JNIEnv *, jclass, jstring, jcharArray, jlong);

/*
 * Class:     BoincAPIWrapper
 * Method:    wuCpuTime
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_wuCpuTime
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     BoincAPIWrapper
 * Method:    elapsedTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_BoincAPIWrapper_elapsedTime
  (JNIEnv *, jclass);

/*
 * Class:     BoincAPIWrapper
 * Method:    uploadFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_uploadFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     BoincAPIWrapper
 * Method:    uploadStatus
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_uploadStatus
  (JNIEnv *, jclass, jstring);

/*
 * Class:     BoincAPIWrapper
 * Method:    msgPrefix
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_BoincAPIWrapper_msgPrefix
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     BoincAPIWrapper
 * Method:    reportAppStatusAux
 * Signature: (DDDIDD)I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_reportAppStatusAux
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jint, jdouble, jdouble);

/*
 * Class:     BoincAPIWrapper
 * Method:    temporaryExit
 * Signature: (ILjava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_BoincAPIWrapper_temporaryExit
  (JNIEnv *, jclass, jint, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
