
JAVAC = $(JDK)/bin/javac
JAVA = $(JDK)/bin/java

all: BoincAPIWrapper Boinc

BoincAPIWrapper:
	$(JAVAC) wrapper/BoincAPIWrapper.java 



Boinc:
	echo Nothing to do here yet...

clean:
	rm wrapper/*.class